### ISSUE TITLE
Possible Issue With Flow.through_specs/3

### ISSUE THREAD

**Issue by ninjanicely** [plataformatec/flow#92]
Hello!

I have a simple flow set up here: https://github.com/ninjanicely/flow_fun which demonstrates my issue.
The "problem" I'm seeing is lack of parallelism when using `Flow.from_spec |> Flow.through_spec`. Here's some example code below..

```elixir

defmodule MyFlow do

  def start_link(_opts) do
    Flow.from_specs([{ A , 1000 }], [max_demand:  1])
    #|> Flow.map(&B.factorial/1)
    |> Flow.through_specs( [ { {B, []} , []} ] )
    |> Flow.into_specs( [ {C, []} ], [] )
  end

end
```

So, brief background, `B` has a factorial function in it, I use that to tax the cpu.
The `handle_events/3` function in `B` calls the factorial function.
If I use `Flow.through_specs/3`, I see roughly 100% cpu usage on my machine (where I would expect to see 400%). When I commented out the `Flow.through_specs/3` line and replace
with the `Flow.map/2` function, I see all cpus being used.

I was hoping that I could force the parallelization in the `Flow.through_specs/3` call, but that doesn't seem to be the case. Am I missing something? Should I see parallelism when configuring a Flow like this?

Thanks!

**Comment by josevalim** [comment]
You are adding a single spec, which means you will have a single process, and we can't scale a single process to multiple cores. Increasing the number of specs should fix it.

**Comment by ninjanicely** [comment]
Ah, thank you!
